spring:
  application:
    name: customer-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/projectlos?currentSchema=customer
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": true
  elasticsearch:
    uris: http://localhost:9200
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/projectlos
          jwk-set-uri: http://localhost:8080/realms/projectlos/protocol/openid-connect/certs

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/projectlos?currentSchema=customer
  elasticsearch:
    uris: http://localhost:9200

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/projectlos?currentSchema=customer}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://elasticsearch:9200}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:projectlos}
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:projectlos}/protocol/openid-connect/certs

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/projectlos?currentSchema=customer
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  elasticsearch:
    uris: ${ELASTICSEARCH_URL:http://localhost:9200}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:projectlos}
          jwk-set-uri: ${KEYCLOAK_AUTH_SERVER_URL:http://localhost:8080}/realms/${KEYCLOAK_REALM:projectlos}/protocol/openid-connect/certs
